version: "3"

services:
  api:
    build: .
    command: gunicorn --bind=0.0.0.0:8000 api:app
    expose:
      - "8000"
    volumes:
      - /mnt/datasets/lfw:/mnt
    environment:
      - REFERENCE_PATH=/mnt/reference.sqlite

  nginx:
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
