version: "3"

services:
  api:
    build: .
    command: gunicorn --bind=0.0.0.0:8000 main:app
    expose:
      - "8000"
    volumes:
      - /mnt:/mnt
    env_file: .env

  nginx:
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
